Name:           perl-Data-Manager
Version:        0.10
Release:        1%{?dist}
Summary:        Marriage of Message::Stack & Data::Verifier
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Data-Manager/
Source0:        https://www.cpan.org/authors/id/G/GP/GPHAT/Data-Manager-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(Data::Verifier)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(JSON::Any)
BuildRequires:  perl(JSON::XS)
BuildRequires:  perl(Message::Stack)
BuildRequires:  perl(Message::Stack::Parser) >= 0.05
BuildRequires:  perl(Message::Stack::Parser::DataVerifier)
BuildRequires:  perl(Moose)
BuildRequires:  perl(MooseX::Storage)
BuildRequires:  perl(MooseX::Storage::Deferred)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::More)
Requires:       perl(JSON::Any)
Requires:       perl(JSON::XS)
Requires:       perl(Message::Stack)
Requires:       perl(Message::Stack::Parser) >= 0.05
Requires:       perl(Message::Stack::Parser::DataVerifier)
Requires:       perl(Moose)
Requires:       perl(MooseX::Storage)
Requires:       perl(MooseX::Storage::Deferred)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Data::Manager provides a convenient mechanism for managing multiple
Data::Verifier inputs with a single Message::Stack, as well as convenient
retrieval of the results of verification.

%prep
%setup -q -n Data-Manager-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes ignore.txt LICENSE META.json README README.mkdn
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jan 31 2023 yaroslav@fedevych.name 0.10-1
- Specfile autogenerated by cpanspec 1.78.
