Name:           perl-Plack-Middleware-ProxyMap
Version:        0.20
Release:        1%{?dist}
Summary:        Proxy Various URLs to Various Remotes
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Plack-Middleware-ProxyMap/
Source0:        https://www.cpan.org/authors/id/I/IN/INGY/Plack-Middleware-ProxyMap-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:v5.8.1
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Plack::App::Proxy)
BuildRequires:  perl(Plack::Middleware)
BuildRequires:  perl(Plack::Util::Accessor)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Pod) >= 1.41
Requires:       perl(Plack::App::Proxy)
Requires:       perl(Plack::Middleware)
Requires:       perl(Plack::Util::Accessor)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
This middleware allows you to easily map one or more URL prefixes to
remote URLs.

%prep
%setup -q -n Plack-Middleware-ProxyMap-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes CONTRIBUTING LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.20-1
- Specfile autogenerated by cpanspec 1.78.
