Name:           perl-URL-Encode
Version:        0.03
Release:        1%{?dist}
Summary:        Encoding and decoding of application/x-www-form-urlencoded encoding
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/URL-Encode/
Source0:        https://www.cpan.org/authors/id/C/CH/CHANSEN/URL-Encode-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  make
BuildRequires:  findutils
BuildRequires:  coreutils
BuildRequires:  perl(Carp)
BuildRequires:  perl(Exporter)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(XSLoader)
BuildRequires:  perl(FindBin)
Requires:       perl(Carp)
Requires:       perl(Exporter)
Requires:       perl(XSLoader)
Requires:       perl(FindBin)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides functions to encode and decode strings into and from
the application/x-www-form-urlencoded encoding.

%prep
%setup -q -n URL-Encode-%{version}

%build
export PERL_USE_UNSAFE_INC=1
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
export PERL_USE_UNSAFE_INC=1
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
export PERL_USE_UNSAFE_INC=1
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jun 13 2023 Yaroslav Fedevych <yaroslav@fedevych.name> 0.03-1
- Specfile autogenerated by cpanspec 1.78.
