Name:           perl-URL-Encode-XS
Version:        0.03
Release:        1%{?dist}
Summary:        XS implementation of URL::Encode
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/URL-Encode-XS/
Source0:        https://www.cpan.org/authors/id/C/CH/CHANSEN/URL-Encode-XS-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl-devel
BuildRequires:  gcc
BuildRequires:  make
BuildRequires:  findutils
BuildRequires:  coreutils
BuildRequires:  perl(Carp)
BuildRequires:  perl(Exporter)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(URL::Encode) >= 0.03
BuildRequires:  perl(XSLoader)
Requires:       perl(Carp)
Requires:       perl(Exporter)
Requires:       perl(URL::Encode) >= 0.03
Requires:       perl(XSLoader)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The main URL::Encode package will use this package automatically if it can
find it. Do not use this package directly, use URL::Encode instead.

%prep
%setup -q -n URL-Encode-XS-%{version}

%build
export PERL_USE_UNSAFE_INC=1
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="%{optflags}"
make %{?_smp_mflags}

%install
export PERL_USE_UNSAFE_INC=1
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
export PERL_USE_UNSAFE_INC=1
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/URL*
%{_mandir}/man3/*

%changelog
* Tue Jun 13 2023 Yaroslav Fedevych <yaroslav@fedevych.name> 0.03-1
- Specfile autogenerated by cpanspec 1.78.
