Name:           perl-Method-Signatures
Version:        20170211
Release:        1%{?dist}
Summary:        Method and function declarations with signatures and no source filter
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Method-Signatures/
Source0:        https://www.cpan.org/authors/id/B/BA/BAREFOOT/Method-Signatures-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl-interpreter >= 1:v5.8.1
BuildRequires:  perl(perl5db.pl)
BuildRequires:  perl(Any::Moose) >= 0.11
BuildRequires:  perl(Const::Fast) >= 0.006
BuildRequires:  perl(Data::Alias) >= 1.08
BuildRequires:  perl(Devel::Declare) >= 0.006002
BuildRequires:  perl(Devel::Declare::MethodInstaller::Simple) >= 0.006002
BuildRequires:  perl(Lexical::SealRequireHints) >= 0.008
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Moose) >= 0.96
BuildRequires:  perl(Mouse) >= 0.64
BuildRequires:  perl(PPI) >= 1.203
BuildRequires:  perl(Sub::Name) >= 0.03
BuildRequires:  perl(Test::Builder) >= 0.82
BuildRequires:  perl(Test::Exception) >= 0.29
BuildRequires:  perl(Test::More) >= 0.82
BuildRequires:  perl(Test::Warn) >= 0.10
Requires:       perl(Any::Moose) >= 0.11
Requires:       perl(Const::Fast) >= 0.006
Requires:       perl(Data::Alias) >= 1.08
Requires:       perl(Devel::Declare) >= 0.006002
Requires:       perl(Devel::Declare::MethodInstaller::Simple) >= 0.006002
Requires:       perl(Lexical::SealRequireHints) >= 0.008
Requires:       perl(Moose) >= 0.96
Requires:       perl(Mouse) >= 0.64
Requires:       perl(PPI) >= 1.203
Requires:       perl(Sub::Name) >= 0.03
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Provides two new keywords, func and method, so that you can write
subroutines with signatures instead of having to spell out my $self =
shift; my($thing) = @_

%prep
%setup -q -n Method-Signatures-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes examples LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Feb 01 2023 yaroslav@fedevych.name 20170211-1
- Specfile autogenerated by cpanspec 1.78.
