Name:           perl-Plack-App-Path-Router
Version:        0.08
Release:        1%{?dist}
Summary:        Plack component for dispatching with Path::Router
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Plack-App-Path-Router/
Source0:        https://www.cpan.org/authors/id/D/DO/DOY/Plack-App-Path-Router-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(IO::Handle)
BuildRequires:  perl(IPC::Open3)
BuildRequires:  perl(Moose) >= 0.90
BuildRequires:  perl(MooseX::NonMoose) >= 0.07
BuildRequires:  perl(Path::Router) >= 0.08
BuildRequires:  perl(Plack::App::URLMap)
BuildRequires:  perl(Plack::Component)
BuildRequires:  perl(Plack::Middleware::Auth::Basic)
BuildRequires:  perl(Plack::Request) >= 0.08
BuildRequires:  perl(Plack::Response)
BuildRequires:  perl(Plack::Test)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Try::Tiny)
BuildRequires:  perl(warnings)
Requires:       perl(Moose) >= 0.90
Requires:       perl(MooseX::NonMoose) >= 0.07
Requires:       perl(Path::Router) >= 0.08
Requires:       perl(Plack::Component)
Requires:       perl(Plack::Request) >= 0.08
Requires:       perl(Try::Tiny)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
This is a Plack::Component subclass which creates an endpoint to dispatch
using Path::Router.

%prep
%setup -q -n Plack-App-Path-Router-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.08-1
- Specfile autogenerated by cpanspec 1.78.
