Name:           perl-WWW-FCM-HTTP
Version:        0.03
Release:        1%{?dist}
Summary:        HTTP Client for Firebase Cloud Messaging
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/WWW-FCM-HTTP/
Source0:        https://www.cpan.org/authors/id/X/XA/XAICRON/WWW-FCM-HTTP-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter >= 0:5.008001
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl(Class::Accessor::Lite)
BuildRequires:  perl(JSON)
BuildRequires:  perl(LWP::ConnCache)
BuildRequires:  perl(LWP::Protocol::https)
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::Fake::HTTPD)
BuildRequires:  perl(Test::More) >= 0.98
BuildRequires:  perl(Test::SharedFork)
BuildRequires:  perl(Module::Build::Tiny)
Requires:       perl(Class::Accessor::Lite)
Requires:       perl(JSON)
Requires:       perl(LWP::ConnCache)
Requires:       perl(LWP::Protocol::https)
Requires:       perl(LWP::UserAgent)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
WWW::FCM::HTTP is a HTTP Clinet for Firebase Cloud Messaging.

%prep
%setup -q -n WWW-FCM-HTTP-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes cpanfile LICENSE META.json minil.toml README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.03-1
- Specfile autogenerated by cpanspec 1.78.
