Name:           perl-POE-Component-Supervisor
Version:        0.09
Release:        1%{?dist}
Summary:        Erlang-inspired babysitting
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/POE-Component-Supervisor/
Source0:        http://www.cpan.org/authors/id/E/ET/ETHER/POE-Component-Supervisor-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl(Devel::PartialDump)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Hash::Util::FieldHash::Compat)
BuildRequires:  perl(Log::Dispatch::Config::TestLog)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Moose)
BuildRequires:  perl(Moose::Role)
BuildRequires:  perl(Moose::Util::TypeConstraints)
BuildRequires:  perl(MooseX::LogDispatch)
BuildRequires:  perl(MooseX::POE) >= 0.210
BuildRequires:  perl(MooseX::POE::Aliased)
BuildRequires:  perl(namespace::autoclean)
BuildRequires:  perl(POE)
BuildRequires:  perl(POE::API::Peek) >= 2.13
BuildRequires:  perl(POE::Wheel::Run)
BuildRequires:  perl(POSIX)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Set::Object)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Time::HiRes)
BuildRequires:  perl(warnings)
Requires:       perl(Devel::PartialDump)
Requires:       perl(Hash::Util::FieldHash::Compat)
Requires:       perl(Moose)
Requires:       perl(Moose::Role)
Requires:       perl(Moose::Util::TypeConstraints)
Requires:       perl(MooseX::LogDispatch)
Requires:       perl(MooseX::POE) >= 0.210
Requires:       perl(MooseX::POE::Aliased)
Requires:       perl(namespace::autoclean)
Requires:       perl(POE::API::Peek) >= 2.13
Requires:       perl(POE::Wheel::Run)
Requires:       perl(POSIX)
Requires:       perl(Scalar::Util)
Requires:       perl(Set::Object)
Requires:       perl(strict)
Requires:       perl(Time::HiRes)
Requires:       perl(warnings)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
This is a port of the Erlang process supervisor
(http://www.erlang.org/doc/design_principles/sup_princ.html).

%prep
%setup -q -n POE-Component-Supervisor-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes CONTRIBUTING dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.09-1
- Specfile autogenerated by cpanspec 1.78.
