Name:           perl-Business-OnlinePayment-AuthorizeNet
Version:        3.23
Release:        1%{?dist}
Summary:        AuthorizeNet backend for Business::OnlinePayment
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Business-OnlinePayment-AuthorizeNet/
Source0:        https://www.cpan.org/authors/id/I/IV/IVAN/Business-OnlinePayment-AuthorizeNet-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(Business::OnlinePayment) >= 3
BuildRequires:  perl(Business::OnlinePayment::HTTPS)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Net::HTTPS::Any)
BuildRequires:  perl(Test::More) >= 0.42
BuildRequires:  perl(Text::CSV_XS)
BuildRequires:  perl(Tie::IxHash)
BuildRequires:  perl(XML::Simple)
BuildRequires:  perl(XML::Writer)
Requires:       perl(Business::OnlinePayment) >= 3
Requires:       perl(Business::OnlinePayment::HTTPS)
Requires:       perl(Net::HTTPS::Any)
Requires:       perl(Test::More) >= 0.42
Requires:       perl(Text::CSV_XS)
Requires:       perl(Tie::IxHash)
Requires:       perl(XML::Simple)
Requires:       perl(XML::Writer)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
For detailed information see Business::OnlinePayment.

%prep
%setup -q -n Business-OnlinePayment-AuthorizeNet-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jan 31 2023 yaroslav@fedevych.name 3.23-1
- Specfile autogenerated by cpanspec 1.78.
