Name:           perl-Net-Dogstatsd
Version:        1.0.3
Release:        1%{?dist}
Summary:        Net::Dogstatsd Perl module
License:        GPL+
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Net-Dogstatsd/
Source0:        https://www.cpan.org/authors/id/J/JP/JPINKHAM/Net-Dogstatsd-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter >= 0:5.006
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl(Carp)
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(Data::Validate::Type)
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Net::Telnet)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Storable)
BuildRequires:  perl(Test::FailWarnings)
BuildRequires:  perl(Test::Most)
BuildRequires:  perl(Try::Tiny)
Requires:       perl(Carp)
Requires:       perl(Data::Dumper)
Requires:       perl(Data::Validate::Type)
Requires:       perl(LWP::UserAgent)
Requires:       perl(Net::Telnet)
Requires:       perl(Try::Tiny)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
DESCRIPTION
-----------
This module provides a simple Perl client to 'dogstatsd', a daemon provided
with the Datadog agent software. The purpose of dogstatsd is to aggregate
the sending of metrics to the Datadog service.  dogstatsd is very similar
to statsd, but supports additional metric types, as well as adding
informational tags to metrics (which makes for easy "slicing and dicing" of
your metrics within the Datadog graphs/dashboards.

%prep
%setup -q -n Net-Dogstatsd-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes ignore.txt LICENSE META.json README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 1.0.3-1
- Specfile autogenerated by cpanspec 1.78.
