Name:           perl-Net-Amazon-Signature-V4
Version:        0.21
Release:        1%{?dist}
Summary:        Implements the Amazon Web Services signature version 4, AWS4-HMAC-SHA256
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Net-Amazon-Signature-V4/
Source0:        https://www.cpan.org/authors/id/D/DB/DBOOK/Net-Amazon-Signature-V4-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  make
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(Digest::SHA)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Slurper)
BuildRequires:  perl(HTTP::Request)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Time::Piece) >= 1.17
BuildRequires:  perl(URI::Escape)
BuildRequires:  perl(sort)
Requires:       perl(Digest::SHA)
Requires:       perl(Time::Piece) >= 1.17
Requires:       perl(URI::Escape)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module signs an HTTP::Request to Amazon Web Services by appending an
Authorization header. Amazon Web Services signature version 4, AWS4-HMAC-
SHA256, is used.

%prep
%setup -q -n Net-Amazon-Signature-V4-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jun 13 2023 Yaroslav Fedevych <yaroslav@fedevych.name> 0.21-1
- Specfile autogenerated by cpanspec 1.78.
