Name:           perl-CGI-Application-Plugin-RunmodeDeclare
Version:        0.10
Release:        1%{?dist}
Summary:        Declare runmodes with keywords
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/CGI-Application-Plugin-RunmodeDeclare/
Source0:        https://www.cpan.org/authors/id/R/RH/RHESA/CGI-Application-Plugin-RunmodeDeclare-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter >= 0:5.008
BuildRequires:  perl-generators
BuildRequires:  make
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl(CGI::Application) >= 4.06
BuildRequires:  perl(Devel::Declare) >= 0.003001
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)
Requires:       perl(CGI::Application) >= 4.06
Requires:       perl(Devel::Declare) >= 0.003001
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
This module allows you to declare run modes with a simple keyword. It
provides the same features as Method::Signatures::Simple.

%prep
%setup -q -n CGI-Application-Plugin-RunmodeDeclare-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jan 31 2023 yaroslav@fedevych.name 0.10-1
- Specfile autogenerated by cpanspec 1.78.
