Name:           perl-Net-APNS-Simple
Version:        0.07
Release:        1%{?dist}
Summary:        APNS Perl implementation
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Net-APNS-Simple/
Source0:        https://www.cpan.org/authors/id/R/RO/ROCKBONE/Net-APNS-Simple-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter >= 0:5.008001
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl(Crypt::JWT) >= 0.018
BuildRequires:  perl(Crypt::PK::ECC) >= 0.059
BuildRequires:  perl(File::Basename)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(IO::Socket::SSL) >= 2.038
BuildRequires:  perl(JSON)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Moo)
BuildRequires:  perl(Net::HTTP)
BuildRequires:  perl(Protocol::HTTP2) >= 1.08
BuildRequires:  perl(Test::More) >= 0.98
BuildRequires:  perl(URI)
BuildRequires:  perl(Module::Build::Tiny)
Requires:       perl(Crypt::JWT) >= 0.018
Requires:       perl(Crypt::PK::ECC) >= 0.059
Requires:       perl(IO::Socket::SSL) >= 2.038
Requires:       perl(JSON)
Requires:       perl(Moo)
Requires:       perl(Net::HTTP)
Requires:       perl(Protocol::HTTP2) >= 1.08
Requires:       perl(URI)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
A Perl implementation for sending notifications via APNS using Apple's new
HTTP/2 API. This library uses Protocol::HTTP2::Client as http2 backend. And
it also supports multiple stream at one connection. (It does not correspond
to parallel stream because APNS server returns
SETTINGS_MAX_CONCURRENT_STREAMS = 1.)

%prep
%setup -q -n Net-APNS-Simple-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes cpanfile LICENSE META.json minil.toml README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.07-1
- Specfile autogenerated by cpanspec 1.78.
