Name:           perl-Business-PayPal-NVP
Version:        1.10
Release:        1%{?dist}
Summary:        PayPal NVP API
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Business-PayPal-NVP/
Source0:        https://www.cpan.org/authors/id/S/SC/SCOTTW/Business-PayPal-NVP-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter >= 0:5.008
BuildRequires:  perl-generators
BuildRequires:  make
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(LWP::Protocol::https)
Requires:       perl(LWP::Protocol::https)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Business::PayPal::NVP makes calls to PayPal's NVP ("name-value pair"--a
fancy name for HTTP POST queries) API.

%prep
%setup -q -n Business-PayPal-NVP-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jan 31 2023 yaroslav@fedevych.name 1.10-1
- Specfile autogenerated by cpanspec 1.78.
