Name:           perl-Business-OnlinePayment
Version:        3.05
Release:        1%{?dist}
Summary:        Perl extension for online payment processing
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Business-OnlinePayment/
Source0:        https://www.cpan.org/authors/id/I/IV/IVAN/Business-OnlinePayment-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Net::HTTPS::Any)
BuildRequires:  perl(Tie::IxHash)
Requires:       perl(Net::HTTPS::Any)
Requires:       perl(Tie::IxHash)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Business::OnlinePayment is a generic module for processing payments through
online credit card processors, electronic cash systems, etc.

%prep
%setup -q -n Business-OnlinePayment-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes META.json notes_for_module_writers notes_for_module_writers_v3 README TODO
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jan 31 2023 yaroslav@fedevych.name 3.05-1
- Specfile autogenerated by cpanspec 1.78.
