Name:           perl-Gazelle
Version:        0.49
Release:        2%{?dist}
Summary:        Preforked Plack Handler for performance freaks
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Gazelle/
Source0:        https://www.cpan.org/authors/id/K/KA/KAZEBURO/Gazelle-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl-interpreter >= 0:5.008001
BuildRequires:  gcc
BuildRequires:  perl-generators
BuildRequires:  perl-devel
BuildRequires:  findutils
BuildRequires:  coreutils
BuildRequires:  perl(Guard)
BuildRequires:  perl(HTTP::Request::Common)
BuildRequires:  perl(HTTP::Tiny) >= 0.058
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Parallel::Prefork) >= 0.18
BuildRequires:  perl(Plack) >= 1.0037
BuildRequires:  perl(Plack::Test)
BuildRequires:  perl(Plack::Test::Suite)
BuildRequires:  perl(Server::Starter)
BuildRequires:  perl(Stream::Buffered)
BuildRequires:  perl(Test::More) >= 0.98
BuildRequires:  perl(Test::TCP) >= 2
BuildRequires:  perl(Devel::CheckCompiler)
Requires:       perl(Guard)
Requires:       perl(Parallel::Prefork) >= 0.18
Requires:       perl(Plack) >= 1.0037
Requires:       perl(Server::Starter)
Requires:       perl(Stream::Buffered)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Gazelle is a PSGI Handler. It is derivied from Starlet. A lot of its code
was rewritten or optimized by converting it to XS code.

%prep
%setup -q -n Gazelle-%{version}

%build
%{__perl} Build.PL --installdirs=vendor --optimize="%{optflags}"
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes cpanfile LICENSE META.json minil.toml README.md
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Gazelle*
%{_mandir}/man3/*

%changelog
* Tue Jan 31 2023 yaroslav@fedevych.name 0.49-2
- Added underspecified Devel::CheckCompiler requirement

* Mon Jan 30 2023 yaroslav@fedevych.name 0.49-1
- Specfile autogenerated by cpanspec 1.78.
