Name:           perl-HTML-Scrubber-StripScripts
Version:        0.02
Release:        2%{?dist}
Summary:        Strip scripting from HTML
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/HTML-Scrubber-StripScripts/
Source0:        https://www.cpan.org/authors/id/N/NC/NCLEATON/HTML-Scrubber-StripScripts-%{version}.tar.gz
Patch0:         perl-HTML-Scrubber-StripScripts-test-fixes.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTML::Scrubber) >= 0.03
BuildRequires:  perl(Test::More)
Requires:       perl(HTML::Scrubber) >= 0.03
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
This module provides a preworked configuration for HTML::Scrubber,
configuring it to leave as much non-scripting markup in place as possible
while being certain to eliminate all scripting constructs. This allows web
applications to display HTML originating from an untrusted source without
introducing XSS (cross site scripting) vulnerabilities.

%prep
%setup -q -n HTML-Scrubber-StripScripts-%{version}
%patch -P 0 -p1

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jun 27 2023 Yaroslav Fedevych <yaroslav@fedevych.name> 0.02-2
- Updated to use a non-deprecated form of %patch

* Wed Feb 01 2023 yaroslav@fedevych.name 0.02-1
- Specfile autogenerated by cpanspec 1.78.
