Name:           perl-DBIx-Class-InflateColumn-Authen-Passphrase
Version:        0.03
Release:        1%{?dist}
Summary:        Inflate/deflate columns to Authen::Passphrase instances
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/DBIx-Class-InflateColumn-Authen-Passphrase/
Source0:        https://www.cpan.org/authors/id/E/ET/ETHER/DBIx-Class-InflateColumn-Authen-Passphrase-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter >= 0:5.006
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(Authen::Passphrase)
BuildRequires:  perl(Authen::Passphrase::BlowfishCrypt)
BuildRequires:  perl(Authen::Passphrase::SaltedDigest)
BuildRequires:  perl(DBD::SQLite)
BuildRequires:  perl(DBIx::Class)
BuildRequires:  perl(DBIx::Class::Core)
BuildRequires:  perl(DBIx::Class::Schema)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(lib)
BuildRequires:  perl(parent)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::More) >= 0.89
BuildRequires:  perl(warnings)
Requires:       perl(Authen::Passphrase)
Requires:       perl(DBIx::Class)
Requires:       perl(parent)
Requires:       perl(strict)
Requires:       perl(warnings)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Provides inflation and deflation for Authen::Passphrase instances from and
to either RFC 2307 or crypt encoding.

%prep
%setup -q -n DBIx-Class-InflateColumn-Authen-Passphrase-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes CONTRIBUTING dist.ini LICENCE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Feb 01 2023 yaroslav@fedevych.name 0.03-1
- Specfile autogenerated by cpanspec 1.78.
