Name:           perl-Finance-OFX-Parse-Simple
Version:        0.07
Release:        1%{?dist}
Summary:        Finance::OFX::Parse::Simple Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Finance-OFX-Parse-Simple/
Source0:        https://www.cpan.org/modules/by-module/Finance/Finance-OFX-Parse-Simple-%{version}.zip
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)

Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Requires:       perl(strict)
Requires:       perl(warnings)
Requires:       perl(POSIX)

%{?perl_default_filter}

%description
Note that this module is primarily intended for the OFX files from bank
statements rather than credit card statements. Any patches to make this
module fully-compliant with the credit card statement style of OFX files
would be gratefully received.

%prep
%setup -q -n Finance--OFX--Parse--Simple-master

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes README README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Feb 02 2023 yaroslav@fedevych.name master-1
- Specfile autogenerated by cpanspec 1.78.
