Name:           perl-XML-Sig
Version:        0.59
Release:        1%{?dist}
Summary:        XML::Sig - A toolkit to help sign and verify XML Digital Signatures
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/XML-Sig/
Source0:        https://www.cpan.org/authors/id/T/TI/TIMLEGGE/XML-Sig-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter >= 0:5.008
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(base)
BuildRequires:  perl(Carp)
BuildRequires:  perl(Class::Accessor)
BuildRequires:  perl(constant)
BuildRequires:  perl(Crypt::Digest::RIPEMD160)
BuildRequires:  perl(Crypt::Mac::HMAC)
BuildRequires:  perl(Crypt::OpenSSL::Bignum)
BuildRequires:  perl(Crypt::OpenSSL::DSA) >= 0.20
BuildRequires:  perl(Crypt::OpenSSL::Guess)
BuildRequires:  perl(Crypt::OpenSSL::RSA)
BuildRequires:  perl(Crypt::OpenSSL::X509)
BuildRequires:  perl(CryptX) >= 0.036
BuildRequires:  perl(Digest::SHA)
BuildRequires:  perl(Encode)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec::Functions)
BuildRequires:  perl(File::Which)
BuildRequires:  perl(MIME::Base64)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::Exception)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(URI)
BuildRequires:  perl(vars)
BuildRequires:  perl(warnings)
BuildRequires:  perl(XML::LibXML)
Requires:       perl(base)
Requires:       perl(Carp)
Requires:       perl(Class::Accessor)
Requires:       perl(constant)
Requires:       perl(Crypt::Digest::RIPEMD160)
Requires:       perl(Crypt::Mac::HMAC)
Requires:       perl(Crypt::OpenSSL::Bignum)
Requires:       perl(Crypt::OpenSSL::DSA) >= 0.20
Requires:       perl(Crypt::OpenSSL::RSA)
Requires:       perl(Crypt::OpenSSL::X509)
Requires:       perl(CryptX) >= 0.036
Requires:       perl(Digest::SHA)
Requires:       perl(Encode)
Requires:       perl(MIME::Base64)
Requires:       perl(strict)
Requires:       perl(URI)
Requires:       perl(vars)
Requires:       perl(warnings)
Requires:       perl(XML::LibXML)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
This perl module provides two primary capabilities: given an XML string,
create and insert digital signatures, or if one is already present in the
string verify it -- all in accordance with the W3C standard governing XML
signatures.

%prep
%setup -q -n XML-Sig-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes cpanfile dist.ini History.md LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.59-1
- Specfile autogenerated by cpanspec 1.78.
