Name:           perl-MooseX-Types-Email
Version:        0.008
Release:        1%{?dist}
Summary:        Email address validation type constraints for Moose
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/MooseX-Types-Email/
Source0:        https://www.cpan.org/authors/id/E/ET/ETHER/MooseX-Types-Email-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter >= 0:5.006
BuildRequires:  perl-generators
BuildRequires:  findutils
BuildRequires:  coreutils
BuildRequires:  perl(Email::Abstract)
BuildRequires:  perl(Email::Valid)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(if)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Module::Build::Tiny)
BuildRequires:  perl(Module::Metadata)
BuildRequires:  perl(MooseX::Types)
BuildRequires:  perl(MooseX::Types::Moose)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::Deep)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(warnings)
Requires:       perl(Email::Abstract)
Requires:       perl(Email::Valid)
Requires:       perl(if)
Requires:       perl(MooseX::Types)
Requires:       perl(MooseX::Types::Moose)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Moose type constraints which uses Email::Valid and Email::Abstract to check
for valid email addresses and messages. Types that support both single
items and an arrayref of items are available.

%prep
%setup -q -n MooseX-Types-Email-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes CONTRIBUTING dist.ini LICENCE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Feb 02 2023 yaroslav@fedevych.name 0.008-1
- Specfile autogenerated by cpanspec 1.78.
