Name:           perl-Plack-Middleware-ServerStatus-Lite
Version:        0.36
Release:        1%{?dist}
Summary:        Show server status like Apache's mod_status
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Plack-Middleware-ServerStatus-Lite/
Source0:        https://www.cpan.org/authors/id/K/KA/KAZEBURO/Plack-Middleware-ServerStatus-Lite-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(B)
BuildRequires:  perl(Capture::Tiny)
BuildRequires:  perl(Getopt::Long) >= 2.38
BuildRequires:  perl(JSON) >= 2.53
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Net::CIDR::Lite)
BuildRequires:  perl(Parallel::Scoreboard) >= 0.03
BuildRequires:  perl(parent)
BuildRequires:  perl(Plack::Middleware)
BuildRequires:  perl(Plack::Test)
BuildRequires:  perl(Pod::Usage)
BuildRequires:  perl(Starman) >= 0.3013
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::SharedFork)
BuildRequires:  perl(Test::TCP) >= 2.00
BuildRequires:  perl(Try::Tiny) >= 0.09
BuildRequires:  procps
Requires:       perl(Getopt::Long) >= 2.38
Requires:       perl(JSON) >= 2.53
Requires:       perl(Net::CIDR::Lite)
Requires:       perl(Parallel::Scoreboard) >= 0.03
Requires:       perl(parent)
Requires:       perl(Plack::Middleware)
Requires:       perl(Pod::Usage)
Requires:       perl(Try::Tiny) >= 0.09
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Plack::Middleware::ServerStatus::Lite is a middleware that display server
status in multiprocess Plack servers such as Starman and Starlet. This
middleware changes status only before and after executing the application.
so cannot monitor keepalive session and network i/o wait.

%prep
%setup -q -n Plack-Middleware-ServerStatus-Lite-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes cpanfile LICENSE META.json README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_mandir}/man1/*
%{_bindir}/server-status

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.36-1
- Specfile autogenerated by cpanspec 1.78.
