Name:           perl-Plack-App-Proxy
Version:        0.29
Release:        1%{?dist}
Summary:        Proxy requests
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Plack-App-Proxy/
Source0:        https://www.cpan.org/authors/id/L/LE/LEEDO/Plack-App-Proxy-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.8.1
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(AnyEvent::HTTP) >= 1.44
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTTP::Headers)
BuildRequires:  perl(IO::Socket::INET)
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(parent)
BuildRequires:  perl(Plack) >= 1.0013
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Test::Requires)
BuildRequires:  perl(Test::TCP)
BuildRequires:  perl(Plack::Component)
BuildRequires:  perl(Plack::Middleware)
BuildRequires:  perl(Plack::Middleware::Lint)
BuildRequires:  perl(Plack::Util::Accessor)
BuildRequires:  perl(AnyEvent::Socket)
BuildRequires:  perl(AnyEvent::Handle)
BuildRequires:  perl(Plack::Test)
Requires:       perl(AnyEvent::HTTP) >= 1.44
Requires:       perl(AnyEvent::Socket)
Requires:       perl(AnyEvent::Handle)
Requires:       perl(HTTP::Headers)
Requires:       perl(LWP::UserAgent)
Requires:       perl(parent)
Requires:       perl(Plack) >= 1.0013
Requires:       perl(Plack::Component)
Requires:       perl(Plack::Util::Accessor)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Plack::App::Proxy is a middleware-aware proxy application for Plack.

%prep
%setup -q -n Plack-App-Proxy-%{version}

%build
export PERL_USE_UNSAFE_INC=1
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
export PERL_USE_UNSAFE_INC=1
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
export PERL_USE_UNSAFE_INC=1
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.29-1
- Specfile autogenerated by cpanspec 1.78.
