Name:           perl-Plack-Session-Store-Transparent
Version:        0.03
Release:        1%{?dist}
Summary:        Session store container which provides transparent access
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Plack-Session-Store-Transparent/
Source0:        https://www.cpan.org/authors/id/I/IL/ILLO/Plack-Session-Store-Transparent-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008005
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Plack::Session::Store) >= 0.20
BuildRequires:  perl(Test::Exception) >= 0.32
BuildRequires:  perl(Test::More) >= 0.98
BuildRequires:  perl(Carp)
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Plack::Util::Accessor)
Requires:       perl(Plack::Session::Store) >= 0.20
Requires:       perl(Carp)
Requires:       perl(strict)
Requires:       perl(warnings)
Requires:       perl(Scalar::Util)
Requires:       perl(Plack::Util::Accessor)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
This will manipulate multiple session stores transparently. This is a
subclass of Plack::Session::Store and implements its full interface.

%prep
%setup -q -n Plack-Session-Store-Transparent-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes cpanfile LICENSE META.json minil.toml README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.03-1
- Specfile autogenerated by cpanspec 1.78.
