Name:           perl-Method-Signatures-Simple-ParseKeyword
Version:        1.12
Release:        1%{?dist}
Summary:        Method::Signatures::Simple::ParseKeyword Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Method-Signatures-Simple-ParseKeyword/
Source0:        https://www.cpan.org/authors/id/R/RH/RHESA/Method-Signatures-Simple-ParseKeyword-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  make
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Parse::Keyword) >= 0.09
BuildRequires:  perl(Sub::Name) >= 0.26
BuildRequires:  perl(Test::More)
Requires:       perl(Parse::Keyword) >= 0.09
Requires:       perl(Sub::Name) >= 0.26
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description



%prep
%setup -q -n Method-Signatures-Simple-ParseKeyword-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Jun 12 2023 Yaroslav Fedevych <yaroslav@fedevych.name> 1.12-1
- Specfile autogenerated by cpanspec 1.78.
