Name:           perl-Business-AuthorizeNet-CIM
Version:        0.17
Release:        1%{?dist}
Summary:        Authorize.Net Customer Information Manager (CIM) Web Services API
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Business-AuthorizeNet-CIM/
Source0:        https://www.cpan.org/authors/id/F/FA/FAYLAND/Business-AuthorizeNet-CIM-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  make
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(IO::Handle)
BuildRequires:  perl(IPC::Open3)
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(XML::Simple)
BuildRequires:  perl(XML::Writer)
BuildRequires:  perl(blib)
Requires:       perl(LWP::UserAgent)
Requires:       perl(XML::Simple)
Requires:       perl(XML::Writer)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Authorize.Net Customer Information Manager (CIM) Web Services API features
are described at http://developer.authorize.net/api/reference/features/cus-
tomer_profiles.html, the API reference is at http://developer.authorize.net/api/reference/#customer-
profiles. Another useful (but deprecated) reference is
http://www.authorize.net/support/CIM_XML_guide.pdf, and the reference XML
schema is at https://api.authorize.net/xml/v1/schema/AnetApiSchema.xsd.

%prep
%setup -q -n Business-AuthorizeNet-CIM-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jun 13 2023 Yaroslav Fedevych <yaroslav@fedevych.name> 0.17-1
- Specfile autogenerated by cpanspec 1.78.
