Name:           perl-Message-Stack-Parser
Version:        0.06
Release:        1%{?dist}
Summary:        Simple role for creating a Message::Stack from things
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Message-Stack-Parser/
Source0:        http://www.cpan.org/authors/id/G/GP/GPHAT/Message-Stack-Parser-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Message::Stack::Message)
BuildRequires:  perl(Moose)
BuildRequires:  perl(Moose::Role)
BuildRequires:  perl(Test::More)
Requires:       perl(Message::Stack::Message)
Requires:       perl(Moose)
Requires:       perl(Moose::Role)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Message::Stack::Parser is a Moose role that is used to implement a parser
for converting something into a Message::Stack. This role is nothing more
than a single required method. The actual point of this dist is to package
some of the parsers separate from Message::Stack or the modules that may do
the conversion. Those are Message::Stack::Parser::DataVerifier and
Message::Stack::Parser::FormValidator.

%prep
%setup -q -n Message-Stack-Parser-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes ignore.txt LICENSE META.json README README.mkdn
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jan 31 2023 yaroslav@fedevych.name 0.06-1
- Specfile autogenerated by cpanspec 1.78.
