Name:           perl-Plack-Session-Store-Redis
Version:        0.05
Release:        1%{?dist}
Summary:        Redis based session store for Plack apps
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Plack-Session-Store-Redis/
Source0:        https://www.cpan.org/authors/id/L/LE/LEEDO/Plack-Session-Store-Redis-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(JSON)
BuildRequires:  perl(Plack)
BuildRequires:  perl(Plack::Session)
BuildRequires:  perl(Plack::Session::State::Cookie)
BuildRequires:  perl(Redis)
BuildRequires:  perl(Test::Exception)
BuildRequires:  perl(Test::Requires)
BuildRequires:  perl(Data::MessagePack)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Storable)
Requires:       perl(JSON)
Requires:       perl(Plack)
Requires:       perl(Plack::Session)
Requires:       perl(Redis)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
This module will store Plack session data on a redis server. NOTE: only
works with redis 1.2.x, which appears to be a limitation of Redis.pm.

%prep
%setup -q -n Plack-Session-Store-Redis-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes ignore.txt META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.05-1
- Specfile autogenerated by cpanspec 1.78.
