Name:           perl-Log-Dispatch-Binlog
Version:        0.02
Release:        1%{?dist}
Summary:        Storable based binary logs
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Log-Dispatch-Binlog/
Source0:        https://www.cpan.org/authors/id/N/NU/NUFFIN/Log-Dispatch-Binlog-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Log::Dispatch::File)
BuildRequires:  perl(Log::Dispatch::Handle)
BuildRequires:  perl(Storable)
BuildRequires:  perl(Test::TempDir)
BuildRequires:  perl(Test::use::ok)
Requires:       perl(Log::Dispatch::File)
Requires:       perl(Log::Dispatch::Handle)
Requires:       perl(Storable)
Requires:       perl(Test::TempDir)
Requires:       perl(Test::use::ok)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
The two classes provide in this distribution provide Storable based binary
logging for Log::Dispatch.

%prep
%setup -q -n Log-Dispatch-Binlog-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc 
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.02-1
- Specfile autogenerated by cpanspec 1.78.
