Name:           perl-Future-Mojo
Version:        1.002
Release:        1%{?dist}
Summary:        Use Future with Mojo::IOLoop
License:        Artistic 2.0
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Future-Mojo/
Source0:        https://www.cpan.org/authors/id/D/DB/DBOOK/Future-Mojo-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl(Carp)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Future) >= 0.36
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Module::Metadata)
BuildRequires:  perl(Mojolicious) >= 7.54
BuildRequires:  perl(parent)
BuildRequires:  perl(Role::Tiny) >= 2.000002
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Test::Identity)
BuildRequires:  perl(Test::More) >= 0.94
BuildRequires:  perl(Test::Needs)
Requires:       perl(Carp)
Requires:       perl(Future) >= 0.36
Requires:       perl(Mojolicious) >= 7.54
Requires:       perl(parent)
Requires:       perl(Role::Tiny) >= 2.000002
Requires:       perl(Scalar::Util)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}


%description
This subclass of Future stores a reference to the associated Mojo::IOLoop
instance, allowing the await method to block until the Future is ready.

%prep
%setup -q -n Future-Mojo-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes CONTRIBUTING.md dist.ini LICENSE META.json prereqs.yml README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Jun 16 2023 Yaroslav Fedevych <yaroslav@fedevych.name> 1.002-1
- Specfile autogenerated by cpanspec 1.78.
