Name:           perl-Message-Stack
Version:        0.22
Release:        1%{?dist}
Summary:        Deal with a "stack" of messages
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Message-Stack/
Source0:        https://www.cpan.org/authors/id/G/GP/GPHAT/Message-Stack-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(Carp)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Moose)
BuildRequires:  perl(MooseX::Aliases)
BuildRequires:  perl(MooseX::Storage)
BuildRequires:  perl(MooseX::Storage::Deferred)
BuildRequires:  perl(MooseX::Types)
BuildRequires:  perl(MooseX::Types::Moose)
BuildRequires:  perl(Test::More)
Requires:       perl(Carp)
Requires:       perl(Moose)
Requires:       perl(MooseX::Aliases)
Requires:       perl(MooseX::Storage)
Requires:       perl(MooseX::Storage::Deferred)
Requires:       perl(MooseX::Types)
Requires:       perl(MooseX::Types::Moose)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Message::Stack provides a mechanism for storing messages until they can be
consumed. A stack is used to retain order of occurrence. Each message may
have a id, level, scope, subject and text. Consult the documentation for
Message::Stack::Message for an explanation of these attributes.

%prep
%setup -q -n Message-Stack-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README README.mkdn
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jan 31 2023 yaroslav@fedevych.name 0.22-1
- Specfile autogenerated by cpanspec 1.78.
