Name:           perl-Log-Dispatch-Config-TestLog
Version:        0.02
Release:        1%{?dist}
Summary:        Set up Log::Dispatch::Config for a test run
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Log-Dispatch-Config-TestLog/
Source0:        https://www.cpan.org/authors/id/N/NU/NUFFIN/Log-Dispatch-Config-TestLog-%{version}.tar.gz
Patch0:         perl-Log-Dispatch-Config-TestLog-tests.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Log::Dispatch::Binlog)
BuildRequires:  perl(Log::Dispatch::Config)
BuildRequires:  perl(Path::Class)
BuildRequires:  perl(Perl::Command)
BuildRequires:  perl(Sub::Override)
BuildRequires:  perl(Test::Builder) >= 0.96
BuildRequires:  perl(Test::Deep)
BuildRequires:  perl(FindBin)
BuildRequires:  perl(Data::Dumper)
Requires:       perl(Log::Dispatch::Binlog)
Requires:       perl(Log::Dispatch::Config)
Requires:       perl(Path::Class)
Requires:       perl(Perl::Command)
Requires:       perl(Sub::Override)
Requires:       perl(Test::Builder) >= 0.96
Requires:       perl(Test::Deep)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
This module will load Log::Dispatch::Config and set things up so that:

%prep
%setup -q -n Log-Dispatch-Config-TestLog-%{version}
%patch0 -p1

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check

PERL5LIB=./lib %{__perl} t/fake_test 2>&1
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.02-1
- Specfile autogenerated by cpanspec 1.78.
