Name:           perl-Perl-LanguageServer
Version:        2.5.0
Release:        1%{?dist}
Summary:        Perl::LanguageServer Perl module
License:        Artistic 2.0
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Perl-LanguageServer/
Source0:        https://www.cpan.org/authors/id/G/GR/GRICHTER/Perl-LanguageServer-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  findutils
BuildRequires:  coreutils
BuildRequires:  make
BuildRequires:  perl(AnyEvent)
BuildRequires:  perl(AnyEvent::AIO)
BuildRequires:  perl(Class::Refresh)
BuildRequires:  perl(Compiler::Lexer) >= 0.23
BuildRequires:  perl(Coro)
BuildRequires:  perl(Data::Dump)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Hash::SafeKeys)
BuildRequires:  perl(IO::AIO)
BuildRequires:  perl(JSON)
BuildRequires:  perl(Moose)
BuildRequires:  perl(PadWalker)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Test::More)
Requires:       perl(AnyEvent)
Requires:       perl(AnyEvent::AIO)
Requires:       perl(Class::Refresh)
Requires:       perl(Compiler::Lexer) >= 0.23
Requires:       perl(Coro)
Requires:       perl(Data::Dump)
Requires:       perl(Hash::SafeKeys)
Requires:       perl(IO::AIO)
Requires:       perl(JSON)
Requires:       perl(Moose)
Requires:       perl(PadWalker)
Requires:       perl(Scalar::Util)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
NOTE: Perl::LanguageServer depend on AnyEvent::AIO and Coro. There is a
      warning that this might not work with newer Perls. It works fine for
      Perl::LanguageServer. So just confirm the warning and install it.

%prep
%setup -q -n Perl-LanguageServer-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc LICENSE META.json
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jun 13 2023 Yaroslav Fedevych <yaroslav@fedevych.name> 2.5.0-1
- Specfile autogenerated by cpanspec 1.78.
