Name:           perl-Compiler-Lexer
Version:        0.23
Release:        1%{?dist}
Summary:        Compiler::Lexer Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Compiler-Lexer/
Source0:        https://www.cpan.org/authors/id/G/GO/GOCCY/Compiler-Lexer-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  findutils
BuildRequires:  coreutils
BuildRequires:  perl-devel
BuildRequires:  gcc
BuildRequires:  perl(Devel::PPPort) >= 3.19
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.59
BuildRequires:  perl(ExtUtils::ParseXS) >= 2.21
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More) >= 0.95
BuildRequires:  perl(XSLoader) >= 0.02
Requires:       perl(XSLoader) >= 0.02
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
my $filename = $ARGV[0]; open my $fh, '<', $filename or die "Cannot open
$filename: $!"; my $script = do { local $/; <$fh> };

%prep
%setup -q -n Compiler-Lexer-%{version}

%build
%{__perl} Build.PL --installdirs=vendor --optimize="%{optflags}"
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes cpanfile cpanfile.snapshot LICENSE META.json minil.toml README.md
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Compiler*
%{_mandir}/man3/*

%changelog
* Tue Jun 13 2023 Yaroslav Fedevych <yaroslav@fedevych.name> 0.23-1
- Specfile autogenerated by cpanspec 1.78.
