Name:           perl-Path-Router
Version:        0.15
Release:        1%{?dist}
Summary:        Tool for routing paths
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Path-Router/
Source0:        http://www.cpan.org/authors/id/N/NE/NEILB/Path-Router-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(B)
BuildRequires:  perl(Carp) >= 1.32
BuildRequires:  perl(Clone::PP) >= 1.04
BuildRequires:  perl(constant) >= 1.24
BuildRequires:  perl(Data::Dumper) >= 2.154
BuildRequires:  perl(Eval::Closure) >= 0.13
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(File::Spec::Unix) >= 3.40
BuildRequires:  perl(IO::Handle)
BuildRequires:  perl(IPC::Open3)
BuildRequires:  perl(Moo) >= 2.000001
BuildRequires:  perl(namespace::clean) >= 0.23
BuildRequires:  perl(Sub::Exporter) >= 0.981
BuildRequires:  perl(Term::ReadLine) >= 1.11
BuildRequires:  perl(Test::Builder) >= 1.001013
BuildRequires:  perl(Test::Deep) >= 0.113
BuildRequires:  perl(Test::Fatal) >= 0.012
BuildRequires:  perl(Test::More) >= 1.001013
BuildRequires:  perl(Try::Tiny) >= 0.19
BuildRequires:  perl(Types::Standard) >= 1.000005
BuildRequires:  perl(Type::Tiny) >= 1.000005
Requires:       perl(B)
Requires:       perl(Carp) >= 1.32
Requires:       perl(Clone::PP) >= 1.04
Requires:       perl(constant) >= 1.24
Requires:       perl(Data::Dumper) >= 2.154
Requires:       perl(Eval::Closure) >= 0.13
Requires:       perl(File::Spec::Unix) >= 3.40
Requires:       perl(Moo) >= 2.000001
Requires:       perl(namespace::clean) >= 0.23
Requires:       perl(Sub::Exporter) >= 0.981
Requires:       perl(Term::ReadLine) >= 1.11
Requires:       perl(Try::Tiny) >= 0.19
Requires:       perl(Types::Standard) >= 1.000005
Requires:       perl(Type::Tiny) >= 1.000005
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
This module provides a way of deconstructing paths into parameters suitable
for dispatching on. It also provides the inverse in that it will take a
list of parameters, and construct an appropriate uri for it.

%prep
%setup -q -n Path-Router-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README TODO
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.15-1
- Specfile autogenerated by cpanspec 1.78.
