Name:           perl-Proc-Supervised-Convenience
Version:        1.01
Release:        1%{?dist}
Summary:        Proc::Supervised::Convenience Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Proc-Supervised-Convenience/
Source0:        https://www.cpan.org/authors/id/R/RH/RHESA/Proc-Supervised-Convenience-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008005
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Moose) >= 1.08
BuildRequires:  perl(POSIX)
BuildRequires:  perl(MooseX::Getopt) >= 0.29
BuildRequires:  perl(POE::Component::Supervisor) >= 0.07
BuildRequires:  perl(POE::Component::Supervisor::Supervised::Proc)
Requires:       perl(Moose) >= 1.08
Requires:       perl(POSIX)
Requires:       perl(MooseX::Getopt) >= 0.29
Requires:       perl(POE::Component::Supervisor) >= 0.07
BuildRequires:  perl(POE::Component::Supervisor::Supervised::Proc)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Proc::Supervised::Convenience Perl module

%prep
%setup -q -n Proc-Supervised-Convenience-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE README README.txt
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 1.01-1
- Specfile autogenerated by cpanspec 1.78.
