Name:           perl-WWW-JSON
Version:        1.02
Release:        1%{?dist}
Summary:        Make working with JSON Web API's as painless as possible
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/WWW-JSON/
Source0:        https://www.cpan.org/authors/id/A/AN/ANTIPASTA/WWW-JSON-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter >= 0:5.008005
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl(JSON::XS) >= 2.33
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Moo) >= 1.001
BuildRequires:  perl(Net::OAuth) >= 0.28
BuildRequires:  perl(Safe::Isa) >= 1.000003
BuildRequires:  perl(Test::Mock::LWP::Dispatch) >= 0.06
BuildRequires:  perl(Test::More) >= 0.98
BuildRequires:  perl(Try::Tiny) >= 0.12
BuildRequires:  perl(URI)
Requires:       perl(JSON::XS) >= 2.33
Requires:       perl(LWP::UserAgent)
Requires:       perl(Moo) >= 1.001
Requires:       perl(Net::OAuth) >= 0.28
Requires:       perl(Safe::Isa) >= 1.000003
Requires:       perl(Try::Tiny) >= 0.12
Requires:       perl(URI)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
WWW::JSON is an easy interface to any modern web API that returns JSON.

%prep
%setup -q -n WWW-JSON-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes cpanfile LICENSE META.json README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 1.02-1
- Specfile autogenerated by cpanspec 1.78.
