Name:           perl-Net-Google-CalendarV3
Version:        0.16
Release:        2%{?dist}
Summary:        Net::Google::CalendarV3 Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Net-Google-CalendarV3/
Source0:        https://www.cpan.org/authors/id/R/RH/RHESA/Net-Google-CalendarV3-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(DateTime::Format::ISO8601)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(JSON::XS)
BuildRequires:  perl(Kavorka)
BuildRequires:  perl(Moose)
BuildRequires:  perl(Try::Tiny)
BuildRequires:  perl(Types::Standard)
BuildRequires:  perl(WWW::JSON)
BuildRequires:  perl(Test::More)
Requires:       perl(DateTime::Format::ISO8601)
Requires:       perl(JSON::XS)
Requires:       perl(Kavorka)
Requires:       perl(Moose)
Requires:       perl(Try::Tiny)
Requires:       perl(Types::Standard)
Requires:       perl(WWW::JSON)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Net::Google::CalendarV3 Perl module

%prep
%setup -q -n Net-Google-CalendarV3-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc dist.ini LICENSE README README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Feb 03 2023 yaroslav@fedevych.name 0.16-2
- Added default filter for perl packages

* Fri Feb 03 2023 yaroslav@fedevych.name 0.16-1
- Specfile autogenerated by cpanspec 1.78.
