Name:           perl-DBIx-Class-PassphraseColumn
Version:        0.05
Release:        1%{?dist}
Summary:        Automatically hash password/passphrase columns
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/DBIx-Class-PassphraseColumn/
Source0:        https://www.cpan.org/authors/id/E/ET/ETHER/DBIx-Class-PassphraseColumn-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter >= 0:5.008
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  perl(Authen::Passphrase::AcceptAll)
BuildRequires:  perl(Authen::Passphrase::RejectAll)
BuildRequires:  perl(DBD::SQLite)
BuildRequires:  perl(DBIx::Class)
BuildRequires:  perl(DBIx::Class::Core)
BuildRequires:  perl(DBIx::Class::InflateColumn::Authen::Passphrase)
BuildRequires:  perl(DBIx::Class::Schema)
BuildRequires:  perl(Encode)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(lib)
BuildRequires:  perl(Module::Runtime)
BuildRequires:  perl(namespace::clean)
BuildRequires:  perl(open)
BuildRequires:  perl(parent)
BuildRequires:  perl(strict)
BuildRequires:  perl(Sub::Name)
BuildRequires:  perl(Test::More) >= 0.89
BuildRequires:  perl(utf8)
BuildRequires:  perl(warnings)
Requires:       perl(DBIx::Class)
Requires:       perl(DBIx::Class::InflateColumn::Authen::Passphrase)
Requires:       perl(Encode)
Requires:       perl(Module::Runtime)
Requires:       perl(namespace::clean)
Requires:       perl(parent)
Requires:       perl(strict)
Requires:       perl(Sub::Name)
Requires:       perl(warnings)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This component can be used to automatically hash password columns using any
scheme supported by Authen::Passphrase whenever the value of these columns
is changed.

%prep
%setup -q -n DBIx-Class-PassphraseColumn-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes CONTRIBUTING dist.ini LICENCE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Feb 01 2023 yaroslav@fedevych.name 0.05-1
- Specfile autogenerated by cpanspec 1.78.
