Name:           perl-Log-Dispatch-File-Rolling
Version:        1.09
Release:        2%{?dist}
Summary:        Object for logging to date/time/pid stamped files
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://search.cpan.org/dist/Log-Dispatch-File-Rolling/
Source0:        https://www.cpan.org/authors/id/J/JA/JACOB/Log-Dispatch-File-Rolling-%{version}.tar.gz
Patch0:         perl-Log-Dispatch-File-Rolling-work-with-LD-259.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  make
BuildRequires:  dos2unix
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Log::Dispatch) >= 2.59
BuildRequires:  perl(Log::Log4perl) >= 0.32
BuildRequires:  perl(Test)
BuildRequires:  perl(Test::More)
Requires:       perl(Log::Dispatch) >= 2.59
Requires:       perl(Log::Log4perl) >= 0.32
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
This module subclasses Log::Dispatch::File for logging to date/time stamped
files. See Log::Dispatch::File for instructions on usage. This module
differs only on the following three points:

%prep
%setup -q -n Log-Dispatch-File-Rolling-%{version}
find . -type f \( -iname '*.pl' -o -name '*.yml' -o -name '*.json' -o -name '*.pm' -o -name '*.t' \) -exec dos2unix '{}' ';'

%patch -P 0 -p1

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jun 27 2023 yaroslav@fedevych.name 1.09-2
- Updated usage of %patch to use a non-deprecated form

* Thu Feb 02 2023 yaroslav@fedevych.name 1.09-1
- Specfile autogenerated by cpanspec 1.78.
